from tests.api_keys_cases import (
    test_expiration_notice_mail_contains_expiration_and_extend_hint,
    test_expiration_reminder_script_retries_failed_notice_and_stops_after_success,
    test_expiration_reminder_script_supports_multi_stage_and_keeps_first_notice_timestamp,
)
